author: Siceron
database: false
description: Bot de modération pour Hovercraft
main: badbot.main.BadBot
name: BadBot
version: 0.1

commands:
	badbot:
		description: Commande principale du plugin

permissions:
	badbot.perm:
		description: Permet au joueur de spam
		default: op